"""subscribers

Revision ID: f219e6ad6146
Revises: e5e995be261f
Create Date: 2024-08-27 15:06:05.066090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f219e6ad6146"
down_revision: Union[str, None] = "e5e995be261f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscriber_id", sa.Integer(), nullable=False),
        sa.Column("subscribed_to_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscribed_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscriber_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
